/* Generated by Yosys 0.57+30 (git sha1 23e4c0e42, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

module obvious_leak(clk, share0, share1, leaked_output);
  input clk;
  wire clk;
  input [7:0] share0;
  wire [7:0] share0;
  input [7:0] share1;
  wire [7:0] share1;
  output [7:0] leaked_output;
  wire [7:0] leaked_output;
  wire U__00_;
  wire U__01_;
  wire U__02_;
  wire U__03_;
  wire U__04_;
  wire U__05_;
  wire U__06_;
  wire U__07_;
  wire [7:0] temp;
  XOR2_X1 U__08_ (
    .A(share1[3]),
    .B(share0[3]),
    .Z(temp[3])
  );
  XOR2_X1 U__09_ (
    .A(share1[4]),
    .B(share0[4]),
    .Z(temp[4])
  );
  XOR2_X1 U__10_ (
    .A(share1[5]),
    .B(share0[5]),
    .Z(temp[5])
  );
  XOR2_X1 U__11_ (
    .A(share1[6]),
    .B(share0[6]),
    .Z(temp[6])
  );
  XOR2_X1 U__12_ (
    .A(share1[7]),
    .B(share0[7]),
    .Z(temp[7])
  );
  XOR2_X1 U__13_ (
    .A(share1[0]),
    .B(share0[0]),
    .Z(temp[0])
  );
  XOR2_X1 U__14_ (
    .A(share1[1]),
    .B(share0[1]),
    .Z(temp[1])
  );
  XOR2_X1 U__15_ (
    .A(share1[2]),
    .B(share0[2]),
    .Z(temp[2])
  );
  DFF_X1 U__16_ (
    .CK(clk),
    .D(temp[0]),
    .Q(leaked_output[0]),
    .QN(U__01_)
  );
  DFF_X1 U__17_ (
    .CK(clk),
    .D(temp[1]),
    .Q(leaked_output[1]),
    .QN(U__02_)
  );
  DFF_X1 U__18_ (
    .CK(clk),
    .D(temp[2]),
    .Q(leaked_output[2]),
    .QN(U__03_)
  );
  DFF_X1 U__19_ (
    .CK(clk),
    .D(temp[3]),
    .Q(leaked_output[3]),
    .QN(U__04_)
  );
  DFF_X1 U__20_ (
    .CK(clk),
    .D(temp[4]),
    .Q(leaked_output[4]),
    .QN(U__05_)
  );
  DFF_X1 U__21_ (
    .CK(clk),
    .D(temp[5]),
    .Q(leaked_output[5]),
    .QN(U__06_)
  );
  DFF_X1 U__22_ (
    .CK(clk),
    .D(temp[6]),
    .Q(leaked_output[6]),
    .QN(U__07_)
  );
  DFF_X1 U__23_ (
    .CK(clk),
    .D(temp[7]),
    .Q(leaked_output[7]),
    .QN(U__00_)
  );
endmodule
