/* Generated by Yosys 0.57+30 (git sha1 23e4c0e42, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

module glitch_vulnerable(clk, rst_n, share0, share1, share2, result);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input [7:0] share0;
  wire [7:0] share0;
  input [7:0] share1;
  wire [7:0] share1;
  input [7:0] share2;
  wire [7:0] share2;
  output [7:0] result;
  wire [7:0] result;
  wire _0_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _1_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _2_;
  wire _30_;
  wire _31_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  wire _7_;
  wire _8_;
  wire _9_;
  NAND2_X1 _32_ (
    .A1(share2[0]),
    .A2(rst_n),
    .ZN(_8_)
  );
  XOR2_X1 _33_ (
    .A(share1[0]),
    .B(share0[0]),
    .Z(_9_)
  );
  NOR2_X1 _34_ (
    .A1(_8_),
    .A2(_9_),
    .ZN(_0_)
  );
  NAND2_X1 _35_ (
    .A1(share2[1]),
    .A2(rst_n),
    .ZN(_10_)
  );
  XOR2_X1 _36_ (
    .A(share1[1]),
    .B(share0[1]),
    .Z(_11_)
  );
  NOR2_X1 _37_ (
    .A1(_10_),
    .A2(_11_),
    .ZN(_1_)
  );
  NAND2_X1 _38_ (
    .A1(share2[2]),
    .A2(rst_n),
    .ZN(_12_)
  );
  XOR2_X1 _39_ (
    .A(share1[2]),
    .B(share0[2]),
    .Z(_13_)
  );
  NOR2_X1 _40_ (
    .A1(_12_),
    .A2(_13_),
    .ZN(_2_)
  );
  NAND2_X1 _41_ (
    .A1(share2[3]),
    .A2(rst_n),
    .ZN(_14_)
  );
  XOR2_X1 _42_ (
    .A(share1[3]),
    .B(share0[3]),
    .Z(_15_)
  );
  NOR2_X1 _43_ (
    .A1(_14_),
    .A2(_15_),
    .ZN(_3_)
  );
  NAND2_X1 _44_ (
    .A1(share2[4]),
    .A2(rst_n),
    .ZN(_16_)
  );
  XOR2_X1 _45_ (
    .A(share1[4]),
    .B(share0[4]),
    .Z(_17_)
  );
  NOR2_X1 _46_ (
    .A1(_16_),
    .A2(_17_),
    .ZN(_4_)
  );
  NAND2_X1 _47_ (
    .A1(share2[5]),
    .A2(rst_n),
    .ZN(_18_)
  );
  XOR2_X1 _48_ (
    .A(share1[5]),
    .B(share0[5]),
    .Z(_19_)
  );
  NOR2_X1 _49_ (
    .A1(_18_),
    .A2(_19_),
    .ZN(_5_)
  );
  NAND2_X1 _50_ (
    .A1(share2[6]),
    .A2(rst_n),
    .ZN(_20_)
  );
  XOR2_X1 _51_ (
    .A(share1[6]),
    .B(share0[6]),
    .Z(_21_)
  );
  NOR2_X1 _52_ (
    .A1(_20_),
    .A2(_21_),
    .ZN(_6_)
  );
  NAND2_X1 _53_ (
    .A1(share2[7]),
    .A2(rst_n),
    .ZN(_22_)
  );
  XOR2_X1 _54_ (
    .A(share1[7]),
    .B(share0[7]),
    .Z(_23_)
  );
  NOR2_X1 _55_ (
    .A1(_22_),
    .A2(_23_),
    .ZN(_7_)
  );
  DFF_X1 _56_ (
    .CK(clk),
    .D(_0_),
    .Q(result[0]),
    .QN(_31_)
  );
  DFF_X1 _57_ (
    .CK(clk),
    .D(_1_),
    .Q(result[1]),
    .QN(_30_)
  );
  DFF_X1 _58_ (
    .CK(clk),
    .D(_2_),
    .Q(result[2]),
    .QN(_29_)
  );
  DFF_X1 _59_ (
    .CK(clk),
    .D(_3_),
    .Q(result[3]),
    .QN(_28_)
  );
  DFF_X1 _60_ (
    .CK(clk),
    .D(_4_),
    .Q(result[4]),
    .QN(_27_)
  );
  DFF_X1 _61_ (
    .CK(clk),
    .D(_5_),
    .Q(result[5]),
    .QN(_26_)
  );
  DFF_X1 _62_ (
    .CK(clk),
    .D(_6_),
    .Q(result[6]),
    .QN(_25_)
  );
  DFF_X1 _63_ (
    .CK(clk),
    .D(_7_),
    .Q(result[7]),
    .QN(_24_)
  );
endmodule
