/* Generated by Yosys 0.57+30 (git sha1 23e4c0e42, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

module non_uniform_shares(clk, rst, secret, random, share0, share1);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input [7:0] secret;
  wire [7:0] secret;
  input [7:0] random;
  wire [7:0] random;
  output [7:0] share0;
  wire [7:0] share0;
  output [7:0] share1;
  wire [7:0] share1;
  wire _0_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _1_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _2_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _3_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _4_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _5_;
  wire _6_;
  wire _7_;
  wire _8_;
  wire _9_;
  DFF_X1 _100_ (
    .CK(clk),
    .D(_4_),
    .Q(share1[4]),
    .QN(_51_)
  );
  DFF_X1 _101_ (
    .CK(clk),
    .D(_5_),
    .Q(share1[5]),
    .QN(_50_)
  );
  DFF_X1 _102_ (
    .CK(clk),
    .D(_6_),
    .Q(share1[6]),
    .QN(_49_)
  );
  DFF_X1 _103_ (
    .CK(clk),
    .D(_7_),
    .Q(share1[7]),
    .QN(_48_)
  );
  DFF_X1 _104_ (
    .CK(clk),
    .D(_8_),
    .Q(share0[0]),
    .QN(_47_)
  );
  DFF_X1 _105_ (
    .CK(clk),
    .D(_9_),
    .Q(share0[1]),
    .QN(_46_)
  );
  DFF_X1 _106_ (
    .CK(clk),
    .D(_10_),
    .Q(share0[2]),
    .QN(_45_)
  );
  DFF_X1 _107_ (
    .CK(clk),
    .D(_11_),
    .Q(share0[3]),
    .QN(_44_)
  );
  DFF_X1 _108_ (
    .CK(clk),
    .D(_12_),
    .Q(share0[4]),
    .QN(_43_)
  );
  DFF_X1 _109_ (
    .CK(clk),
    .D(_13_),
    .Q(share0[5]),
    .QN(_42_)
  );
  DFF_X1 _110_ (
    .CK(clk),
    .D(_14_),
    .Q(share0[6]),
    .QN(_41_)
  );
  DFF_X1 _111_ (
    .CK(clk),
    .D(_15_),
    .Q(share0[7]),
    .QN(_40_)
  );
  NAND2_X1 _56_ (
    .A1(random[0]),
    .A2(secret[0]),
    .ZN(_16_)
  );
  NOR2_X1 _57_ (
    .A1(random[0]),
    .A2(secret[0]),
    .ZN(_17_)
  );
  NOR2_X1 _58_ (
    .A1(rst),
    .A2(_17_),
    .ZN(_18_)
  );
  AND2_X1 _59_ (
    .A1(_16_),
    .A2(_18_),
    .ZN(_0_)
  );
  NAND2_X1 _60_ (
    .A1(random[1]),
    .A2(secret[1]),
    .ZN(_19_)
  );
  NOR2_X1 _61_ (
    .A1(random[1]),
    .A2(secret[1]),
    .ZN(_20_)
  );
  NOR2_X1 _62_ (
    .A1(rst),
    .A2(_20_),
    .ZN(_21_)
  );
  AND2_X1 _63_ (
    .A1(_19_),
    .A2(_21_),
    .ZN(_1_)
  );
  NAND2_X1 _64_ (
    .A1(random[2]),
    .A2(secret[2]),
    .ZN(_22_)
  );
  NOR2_X1 _65_ (
    .A1(random[2]),
    .A2(secret[2]),
    .ZN(_23_)
  );
  NOR2_X1 _66_ (
    .A1(rst),
    .A2(_23_),
    .ZN(_24_)
  );
  AND2_X1 _67_ (
    .A1(_22_),
    .A2(_24_),
    .ZN(_2_)
  );
  NAND2_X1 _68_ (
    .A1(random[3]),
    .A2(secret[3]),
    .ZN(_25_)
  );
  NOR2_X1 _69_ (
    .A1(random[3]),
    .A2(secret[3]),
    .ZN(_26_)
  );
  NOR2_X1 _70_ (
    .A1(rst),
    .A2(_26_),
    .ZN(_27_)
  );
  AND2_X1 _71_ (
    .A1(_25_),
    .A2(_27_),
    .ZN(_3_)
  );
  NAND2_X1 _72_ (
    .A1(random[4]),
    .A2(secret[4]),
    .ZN(_28_)
  );
  NOR2_X1 _73_ (
    .A1(random[4]),
    .A2(secret[4]),
    .ZN(_29_)
  );
  NOR2_X1 _74_ (
    .A1(rst),
    .A2(_29_),
    .ZN(_30_)
  );
  AND2_X1 _75_ (
    .A1(_28_),
    .A2(_30_),
    .ZN(_4_)
  );
  NAND2_X1 _76_ (
    .A1(random[5]),
    .A2(secret[5]),
    .ZN(_31_)
  );
  NOR2_X1 _77_ (
    .A1(random[5]),
    .A2(secret[5]),
    .ZN(_32_)
  );
  NOR2_X1 _78_ (
    .A1(rst),
    .A2(_32_),
    .ZN(_33_)
  );
  AND2_X1 _79_ (
    .A1(_31_),
    .A2(_33_),
    .ZN(_5_)
  );
  NAND2_X1 _80_ (
    .A1(random[6]),
    .A2(secret[6]),
    .ZN(_34_)
  );
  NOR2_X1 _81_ (
    .A1(random[6]),
    .A2(secret[6]),
    .ZN(_35_)
  );
  NOR2_X1 _82_ (
    .A1(rst),
    .A2(_35_),
    .ZN(_36_)
  );
  AND2_X1 _83_ (
    .A1(_34_),
    .A2(_36_),
    .ZN(_6_)
  );
  NAND2_X1 _84_ (
    .A1(random[7]),
    .A2(secret[7]),
    .ZN(_37_)
  );
  NOR2_X1 _85_ (
    .A1(random[7]),
    .A2(secret[7]),
    .ZN(_38_)
  );
  NOR2_X1 _86_ (
    .A1(rst),
    .A2(_38_),
    .ZN(_39_)
  );
  AND2_X1 _87_ (
    .A1(_37_),
    .A2(_39_),
    .ZN(_7_)
  );
  NOR2_X1 _88_ (
    .A1(rst),
    .A2(_16_),
    .ZN(_8_)
  );
  NOR2_X1 _89_ (
    .A1(rst),
    .A2(_19_),
    .ZN(_9_)
  );
  NOR2_X1 _90_ (
    .A1(rst),
    .A2(_22_),
    .ZN(_10_)
  );
  NOR2_X1 _91_ (
    .A1(rst),
    .A2(_25_),
    .ZN(_11_)
  );
  NOR2_X1 _92_ (
    .A1(rst),
    .A2(_28_),
    .ZN(_12_)
  );
  NOR2_X1 _93_ (
    .A1(rst),
    .A2(_31_),
    .ZN(_13_)
  );
  NOR2_X1 _94_ (
    .A1(rst),
    .A2(_34_),
    .ZN(_14_)
  );
  NOR2_X1 _95_ (
    .A1(rst),
    .A2(_37_),
    .ZN(_15_)
  );
  DFF_X1 _96_ (
    .CK(clk),
    .D(_0_),
    .Q(share1[0]),
    .QN(_55_)
  );
  DFF_X1 _97_ (
    .CK(clk),
    .D(_1_),
    .Q(share1[1]),
    .QN(_54_)
  );
  DFF_X1 _98_ (
    .CK(clk),
    .D(_2_),
    .Q(share1[2]),
    .QN(_53_)
  );
  DFF_X1 _99_ (
    .CK(clk),
    .D(_3_),
    .Q(share1[3]),
    .QN(_52_)
  );
endmodule
