/* Generated by Yosys 0.57+30 (git sha1 23e4c0e42, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

module pni_violation(clk, rst, x_share0, x_share1, y_share0, y_share1, random, z_share0, z_share1);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input [3:0] x_share0;
  wire [3:0] x_share0;
  input [3:0] x_share1;
  wire [3:0] x_share1;
  input [3:0] y_share0;
  wire [3:0] y_share0;
  input [3:0] y_share1;
  wire [3:0] y_share1;
  input [3:0] random;
  wire [3:0] random;
  output [3:0] z_share0;
  wire [3:0] z_share0;
  output [3:0] z_share1;
  wire [3:0] z_share1;
  wire _0_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _1_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _2_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _3_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _4_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  wire _59_;
  wire _5_;
  wire _60_;
  wire _61_;
  wire _62_;
  wire _63_;
  wire _64_;
  wire _65_;
  wire _66_;
  wire _67_;
  wire _68_;
  wire _69_;
  wire _6_;
  wire _70_;
  wire _71_;
  wire _72_;
  wire _73_;
  wire _74_;
  wire _75_;
  wire _76_;
  wire _77_;
  wire _78_;
  wire _79_;
  wire _7_;
  wire _80_;
  wire _81_;
  wire _82_;
  wire _83_;
  wire _84_;
  wire _85_;
  wire _86_;
  wire _87_;
  wire _8_;
  wire _9_;
  wire [3:0] cross_term;
  wire [3:0] partial0;
  wire [3:0] partial1;
  XNOR2_X1 _100_ (
    .A(random[2]),
    .B(partial0[2]),
    .ZN(_41_)
  );
  NOR2_X1 _101_ (
    .A1(rst),
    .A2(_41_),
    .ZN(_6_)
  );
  XNOR2_X1 _102_ (
    .A(random[3]),
    .B(partial0[3]),
    .ZN(_42_)
  );
  NOR2_X1 _103_ (
    .A1(rst),
    .A2(_42_),
    .ZN(_7_)
  );
  XOR2_X1 _104_ (
    .A(cross_term[0]),
    .B(partial1[0]),
    .Z(_43_)
  );
  NAND2_X1 _105_ (
    .A1(random[0]),
    .A2(_43_),
    .ZN(_44_)
  );
  NOR2_X1 _106_ (
    .A1(random[0]),
    .A2(_43_),
    .ZN(_45_)
  );
  NOR2_X1 _107_ (
    .A1(rst),
    .A2(_45_),
    .ZN(_46_)
  );
  AND2_X1 _108_ (
    .A1(_44_),
    .A2(_46_),
    .ZN(_8_)
  );
  XOR2_X1 _109_ (
    .A(cross_term[1]),
    .B(partial1[1]),
    .Z(_47_)
  );
  NAND2_X1 _110_ (
    .A1(random[1]),
    .A2(_47_),
    .ZN(_48_)
  );
  NOR2_X1 _111_ (
    .A1(random[1]),
    .A2(_47_),
    .ZN(_49_)
  );
  NOR2_X1 _112_ (
    .A1(rst),
    .A2(_49_),
    .ZN(_50_)
  );
  AND2_X1 _113_ (
    .A1(_48_),
    .A2(_50_),
    .ZN(_9_)
  );
  XOR2_X1 _114_ (
    .A(cross_term[2]),
    .B(partial1[2]),
    .Z(_51_)
  );
  NAND2_X1 _115_ (
    .A1(random[2]),
    .A2(_51_),
    .ZN(_52_)
  );
  NOR2_X1 _116_ (
    .A1(random[2]),
    .A2(_51_),
    .ZN(_53_)
  );
  NOR2_X1 _117_ (
    .A1(rst),
    .A2(_53_),
    .ZN(_54_)
  );
  AND2_X1 _118_ (
    .A1(_52_),
    .A2(_54_),
    .ZN(_10_)
  );
  XOR2_X1 _119_ (
    .A(cross_term[3]),
    .B(partial1[3]),
    .Z(_55_)
  );
  NAND2_X1 _120_ (
    .A1(random[3]),
    .A2(_55_),
    .ZN(_56_)
  );
  NOR2_X1 _121_ (
    .A1(random[3]),
    .A2(_55_),
    .ZN(_57_)
  );
  NOR2_X1 _122_ (
    .A1(rst),
    .A2(_57_),
    .ZN(_58_)
  );
  AND2_X1 _123_ (
    .A1(_56_),
    .A2(_58_),
    .ZN(_11_)
  );
  NAND2_X1 _124_ (
    .A1(y_share0[0]),
    .A2(x_share1[0]),
    .ZN(_59_)
  );
  NAND2_X1 _125_ (
    .A1(x_share0[0]),
    .A2(y_share1[0]),
    .ZN(_60_)
  );
  NAND2_X1 _126_ (
    .A1(_59_),
    .A2(_60_),
    .ZN(_61_)
  );
  NOR2_X1 _127_ (
    .A1(_59_),
    .A2(_60_),
    .ZN(_62_)
  );
  NOR2_X1 _128_ (
    .A1(rst),
    .A2(_62_),
    .ZN(_63_)
  );
  AND2_X1 _129_ (
    .A1(_61_),
    .A2(_63_),
    .ZN(_12_)
  );
  NAND2_X1 _130_ (
    .A1(y_share0[1]),
    .A2(x_share1[1]),
    .ZN(_64_)
  );
  NAND2_X1 _131_ (
    .A1(x_share0[1]),
    .A2(y_share1[1]),
    .ZN(_65_)
  );
  NAND2_X1 _132_ (
    .A1(_64_),
    .A2(_65_),
    .ZN(_66_)
  );
  NOR2_X1 _133_ (
    .A1(_64_),
    .A2(_65_),
    .ZN(_67_)
  );
  NOR2_X1 _134_ (
    .A1(rst),
    .A2(_67_),
    .ZN(_20_)
  );
  AND2_X1 _135_ (
    .A1(_66_),
    .A2(_20_),
    .ZN(_13_)
  );
  NAND2_X1 _136_ (
    .A1(y_share0[2]),
    .A2(x_share1[2]),
    .ZN(_21_)
  );
  NAND2_X1 _137_ (
    .A1(x_share0[2]),
    .A2(y_share1[2]),
    .ZN(_22_)
  );
  NAND2_X1 _138_ (
    .A1(_21_),
    .A2(_22_),
    .ZN(_23_)
  );
  NOR2_X1 _139_ (
    .A1(_21_),
    .A2(_22_),
    .ZN(_24_)
  );
  NOR2_X1 _140_ (
    .A1(rst),
    .A2(_24_),
    .ZN(_25_)
  );
  AND2_X1 _141_ (
    .A1(_23_),
    .A2(_25_),
    .ZN(_14_)
  );
  NAND2_X1 _142_ (
    .A1(y_share0[3]),
    .A2(x_share1[3]),
    .ZN(_26_)
  );
  NAND2_X1 _143_ (
    .A1(x_share0[3]),
    .A2(y_share1[3]),
    .ZN(_27_)
  );
  NAND2_X1 _144_ (
    .A1(_26_),
    .A2(_27_),
    .ZN(_28_)
  );
  NOR2_X1 _145_ (
    .A1(_26_),
    .A2(_27_),
    .ZN(_29_)
  );
  NOR2_X1 _146_ (
    .A1(rst),
    .A2(_29_),
    .ZN(_30_)
  );
  AND2_X1 _147_ (
    .A1(_28_),
    .A2(_30_),
    .ZN(_15_)
  );
  NAND2_X1 _148_ (
    .A1(y_share0[0]),
    .A2(x_share0[0]),
    .ZN(_31_)
  );
  NOR2_X1 _149_ (
    .A1(rst),
    .A2(_31_),
    .ZN(_16_)
  );
  NAND2_X1 _150_ (
    .A1(y_share0[1]),
    .A2(x_share0[1]),
    .ZN(_32_)
  );
  NOR2_X1 _151_ (
    .A1(rst),
    .A2(_32_),
    .ZN(_17_)
  );
  NAND2_X1 _152_ (
    .A1(y_share0[2]),
    .A2(x_share0[2]),
    .ZN(_33_)
  );
  NOR2_X1 _153_ (
    .A1(rst),
    .A2(_33_),
    .ZN(_18_)
  );
  NAND2_X1 _154_ (
    .A1(y_share0[3]),
    .A2(x_share0[3]),
    .ZN(_34_)
  );
  NOR2_X1 _155_ (
    .A1(rst),
    .A2(_34_),
    .ZN(_19_)
  );
  DFF_X1 _156_ (
    .CK(clk),
    .D(_0_),
    .Q(partial1[0]),
    .QN(_87_)
  );
  DFF_X1 _157_ (
    .CK(clk),
    .D(_1_),
    .Q(partial1[1]),
    .QN(_86_)
  );
  DFF_X1 _158_ (
    .CK(clk),
    .D(_2_),
    .Q(partial1[2]),
    .QN(_85_)
  );
  DFF_X1 _159_ (
    .CK(clk),
    .D(_3_),
    .Q(partial1[3]),
    .QN(_84_)
  );
  DFF_X1 _160_ (
    .CK(clk),
    .D(_4_),
    .Q(z_share0[0]),
    .QN(_83_)
  );
  DFF_X1 _161_ (
    .CK(clk),
    .D(_5_),
    .Q(z_share0[1]),
    .QN(_82_)
  );
  DFF_X1 _162_ (
    .CK(clk),
    .D(_6_),
    .Q(z_share0[2]),
    .QN(_81_)
  );
  DFF_X1 _163_ (
    .CK(clk),
    .D(_7_),
    .Q(z_share0[3]),
    .QN(_80_)
  );
  DFF_X1 _164_ (
    .CK(clk),
    .D(_8_),
    .Q(z_share1[0]),
    .QN(_79_)
  );
  DFF_X1 _165_ (
    .CK(clk),
    .D(_9_),
    .Q(z_share1[1]),
    .QN(_78_)
  );
  DFF_X1 _166_ (
    .CK(clk),
    .D(_10_),
    .Q(z_share1[2]),
    .QN(_77_)
  );
  DFF_X1 _167_ (
    .CK(clk),
    .D(_11_),
    .Q(z_share1[3]),
    .QN(_76_)
  );
  DFF_X1 _168_ (
    .CK(clk),
    .D(_12_),
    .Q(cross_term[0]),
    .QN(_75_)
  );
  DFF_X1 _169_ (
    .CK(clk),
    .D(_13_),
    .Q(cross_term[1]),
    .QN(_74_)
  );
  DFF_X1 _170_ (
    .CK(clk),
    .D(_14_),
    .Q(cross_term[2]),
    .QN(_73_)
  );
  DFF_X1 _171_ (
    .CK(clk),
    .D(_15_),
    .Q(cross_term[3]),
    .QN(_72_)
  );
  DFF_X1 _172_ (
    .CK(clk),
    .D(_16_),
    .Q(partial0[0]),
    .QN(_71_)
  );
  DFF_X1 _173_ (
    .CK(clk),
    .D(_17_),
    .Q(partial0[1]),
    .QN(_70_)
  );
  DFF_X1 _174_ (
    .CK(clk),
    .D(_18_),
    .Q(partial0[2]),
    .QN(_69_)
  );
  DFF_X1 _175_ (
    .CK(clk),
    .D(_19_),
    .Q(partial0[3]),
    .QN(_68_)
  );
  NAND2_X1 _88_ (
    .A1(y_share1[0]),
    .A2(x_share1[0]),
    .ZN(_35_)
  );
  NOR2_X1 _89_ (
    .A1(rst),
    .A2(_35_),
    .ZN(_0_)
  );
  NAND2_X1 _90_ (
    .A1(y_share1[1]),
    .A2(x_share1[1]),
    .ZN(_36_)
  );
  NOR2_X1 _91_ (
    .A1(rst),
    .A2(_36_),
    .ZN(_1_)
  );
  NAND2_X1 _92_ (
    .A1(y_share1[2]),
    .A2(x_share1[2]),
    .ZN(_37_)
  );
  NOR2_X1 _93_ (
    .A1(rst),
    .A2(_37_),
    .ZN(_2_)
  );
  NAND2_X1 _94_ (
    .A1(y_share1[3]),
    .A2(x_share1[3]),
    .ZN(_38_)
  );
  NOR2_X1 _95_ (
    .A1(rst),
    .A2(_38_),
    .ZN(_3_)
  );
  XNOR2_X1 _96_ (
    .A(random[0]),
    .B(partial0[0]),
    .ZN(_39_)
  );
  NOR2_X1 _97_ (
    .A1(rst),
    .A2(_39_),
    .ZN(_4_)
  );
  XNOR2_X1 _98_ (
    .A(random[1]),
    .B(partial0[1]),
    .ZN(_40_)
  );
  NOR2_X1 _99_ (
    .A1(rst),
    .A2(_40_),
    .ZN(_5_)
  );
endmodule
