/* Generated by Yosys 0.57+30 (git sha1 23e4c0e42, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

module first_order_probing(clk, rst_n, secret_a, secret_b, mask_a, mask_b, result);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input [7:0] secret_a;
  wire [7:0] secret_a;
  input [7:0] secret_b;
  wire [7:0] secret_b;
  input [7:0] mask_a;
  wire [7:0] mask_a;
  input [7:0] mask_b;
  wire [7:0] mask_b;
  output [7:0] result;
  wire [7:0] result;
  wire _0_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _1_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _2_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _3_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _4_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _5_;
  wire _6_;
  wire _7_;
  wire _8_;
  wire _9_;
  AND2_X1 _100_ (
    .A1(rst_n),
    .A2(_4_),
    .ZN(result[4])
  );
  AND2_X1 _101_ (
    .A1(rst_n),
    .A2(_5_),
    .ZN(result[5])
  );
  AND2_X1 _102_ (
    .A1(rst_n),
    .A2(_6_),
    .ZN(result[6])
  );
  AND2_X1 _103_ (
    .A1(rst_n),
    .A2(_7_),
    .ZN(result[7])
  );
  DFF_X1 _104_ (
    .CK(clk),
    .D(_15_),
    .Q(_0_),
    .QN(_48_)
  );
  DFF_X1 _105_ (
    .CK(clk),
    .D(_14_),
    .Q(_1_),
    .QN(_49_)
  );
  DFF_X1 _106_ (
    .CK(clk),
    .D(_13_),
    .Q(_2_),
    .QN(_50_)
  );
  DFF_X1 _107_ (
    .CK(clk),
    .D(_12_),
    .Q(_3_),
    .QN(_51_)
  );
  DFF_X1 _108_ (
    .CK(clk),
    .D(_11_),
    .Q(_4_),
    .QN(_52_)
  );
  DFF_X1 _109_ (
    .CK(clk),
    .D(_10_),
    .Q(_5_),
    .QN(_53_)
  );
  DFF_X1 _110_ (
    .CK(clk),
    .D(_9_),
    .Q(_6_),
    .QN(_54_)
  );
  DFF_X1 _111_ (
    .CK(clk),
    .D(_8_),
    .Q(_7_),
    .QN(_55_)
  );
  AND2_X1 _56_ (
    .A1(secret_a[7]),
    .A2(secret_b[7]),
    .ZN(_16_)
  );
  NAND2_X1 _57_ (
    .A1(mask_a[7]),
    .A2(_16_),
    .ZN(_17_)
  );
  NOR2_X1 _58_ (
    .A1(mask_a[7]),
    .A2(_16_),
    .ZN(_18_)
  );
  NAND2_X1 _59_ (
    .A1(rst_n),
    .A2(_17_),
    .ZN(_19_)
  );
  NOR2_X1 _60_ (
    .A1(_18_),
    .A2(_19_),
    .ZN(_8_)
  );
  AND2_X1 _61_ (
    .A1(secret_a[6]),
    .A2(secret_b[6]),
    .ZN(_20_)
  );
  NAND2_X1 _62_ (
    .A1(mask_a[6]),
    .A2(_20_),
    .ZN(_21_)
  );
  NOR2_X1 _63_ (
    .A1(mask_a[6]),
    .A2(_20_),
    .ZN(_22_)
  );
  NAND2_X1 _64_ (
    .A1(rst_n),
    .A2(_21_),
    .ZN(_23_)
  );
  NOR2_X1 _65_ (
    .A1(_22_),
    .A2(_23_),
    .ZN(_9_)
  );
  AND2_X1 _66_ (
    .A1(secret_a[5]),
    .A2(secret_b[5]),
    .ZN(_24_)
  );
  NAND2_X1 _67_ (
    .A1(mask_a[5]),
    .A2(_24_),
    .ZN(_25_)
  );
  NOR2_X1 _68_ (
    .A1(mask_a[5]),
    .A2(_24_),
    .ZN(_26_)
  );
  NAND2_X1 _69_ (
    .A1(rst_n),
    .A2(_25_),
    .ZN(_27_)
  );
  NOR2_X1 _70_ (
    .A1(_26_),
    .A2(_27_),
    .ZN(_10_)
  );
  AND2_X1 _71_ (
    .A1(secret_a[4]),
    .A2(secret_b[4]),
    .ZN(_28_)
  );
  NAND2_X1 _72_ (
    .A1(mask_a[4]),
    .A2(_28_),
    .ZN(_29_)
  );
  NOR2_X1 _73_ (
    .A1(mask_a[4]),
    .A2(_28_),
    .ZN(_30_)
  );
  NAND2_X1 _74_ (
    .A1(rst_n),
    .A2(_29_),
    .ZN(_31_)
  );
  NOR2_X1 _75_ (
    .A1(_30_),
    .A2(_31_),
    .ZN(_11_)
  );
  AND2_X1 _76_ (
    .A1(secret_a[3]),
    .A2(secret_b[3]),
    .ZN(_32_)
  );
  NAND2_X1 _77_ (
    .A1(mask_a[3]),
    .A2(_32_),
    .ZN(_33_)
  );
  NOR2_X1 _78_ (
    .A1(mask_a[3]),
    .A2(_32_),
    .ZN(_34_)
  );
  NAND2_X1 _79_ (
    .A1(rst_n),
    .A2(_33_),
    .ZN(_35_)
  );
  NOR2_X1 _80_ (
    .A1(_34_),
    .A2(_35_),
    .ZN(_12_)
  );
  AND2_X1 _81_ (
    .A1(secret_a[2]),
    .A2(secret_b[2]),
    .ZN(_36_)
  );
  NAND2_X1 _82_ (
    .A1(mask_a[2]),
    .A2(_36_),
    .ZN(_37_)
  );
  NOR2_X1 _83_ (
    .A1(mask_a[2]),
    .A2(_36_),
    .ZN(_38_)
  );
  NAND2_X1 _84_ (
    .A1(rst_n),
    .A2(_37_),
    .ZN(_39_)
  );
  NOR2_X1 _85_ (
    .A1(_38_),
    .A2(_39_),
    .ZN(_13_)
  );
  AND2_X1 _86_ (
    .A1(secret_a[1]),
    .A2(secret_b[1]),
    .ZN(_40_)
  );
  NAND2_X1 _87_ (
    .A1(mask_a[1]),
    .A2(_40_),
    .ZN(_41_)
  );
  NOR2_X1 _88_ (
    .A1(mask_a[1]),
    .A2(_40_),
    .ZN(_42_)
  );
  NAND2_X1 _89_ (
    .A1(rst_n),
    .A2(_41_),
    .ZN(_43_)
  );
  NOR2_X1 _90_ (
    .A1(_42_),
    .A2(_43_),
    .ZN(_14_)
  );
  AND2_X1 _91_ (
    .A1(secret_a[0]),
    .A2(secret_b[0]),
    .ZN(_44_)
  );
  NAND2_X1 _92_ (
    .A1(mask_a[0]),
    .A2(_44_),
    .ZN(_45_)
  );
  NOR2_X1 _93_ (
    .A1(mask_a[0]),
    .A2(_44_),
    .ZN(_46_)
  );
  NAND2_X1 _94_ (
    .A1(rst_n),
    .A2(_45_),
    .ZN(_47_)
  );
  NOR2_X1 _95_ (
    .A1(_46_),
    .A2(_47_),
    .ZN(_15_)
  );
  AND2_X1 _96_ (
    .A1(rst_n),
    .A2(_0_),
    .ZN(result[0])
  );
  AND2_X1 _97_ (
    .A1(rst_n),
    .A2(_1_),
    .ZN(result[1])
  );
  AND2_X1 _98_ (
    .A1(rst_n),
    .A2(_2_),
    .ZN(result[2])
  );
  AND2_X1 _99_ (
    .A1(rst_n),
    .A2(_3_),
    .ZN(result[3])
  );
endmodule
