/* Generated by Yosys 0.57+30 (git sha1 23e4c0e42, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

module address_resolver(mapping, addri, addro);
  input [1:0] mapping;
  wire [1:0] mapping;
  input [5:0] addri;
  wire [5:0] addri;
  output [5:0] addro;
  wire [5:0] addro;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  INV_X1 _27_ (
    .A(mapping[0]),
    .ZN(_00_)
  );
  NOR2_X1 _28_ (
    .A1(_00_),
    .A2(mapping[1]),
    .ZN(_01_)
  );
  NAND2_X1 _29_ (
    .A1(addri[2]),
    .A2(_01_),
    .ZN(_02_)
  );
  NAND2_X1 _30_ (
    .A1(mapping[1]),
    .A2(addri[0]),
    .ZN(_03_)
  );
  NOR2_X1 _31_ (
    .A1(mapping[0]),
    .A2(mapping[1]),
    .ZN(_04_)
  );
  NAND2_X1 _32_ (
    .A1(addri[4]),
    .A2(_04_),
    .ZN(_05_)
  );
  AND2_X1 _33_ (
    .A1(_03_),
    .A2(_05_),
    .ZN(_06_)
  );
  NAND2_X1 _34_ (
    .A1(_02_),
    .A2(_06_),
    .ZN(addro[0])
  );
  NAND2_X1 _35_ (
    .A1(addri[3]),
    .A2(_01_),
    .ZN(_07_)
  );
  NAND2_X1 _36_ (
    .A1(mapping[1]),
    .A2(addri[1]),
    .ZN(_08_)
  );
  NAND2_X1 _37_ (
    .A1(addri[5]),
    .A2(_04_),
    .ZN(_09_)
  );
  AND2_X1 _38_ (
    .A1(_08_),
    .A2(_09_),
    .ZN(_10_)
  );
  NAND2_X1 _39_ (
    .A1(_07_),
    .A2(_10_),
    .ZN(addro[1])
  );
  NAND2_X1 _40_ (
    .A1(addri[4]),
    .A2(_01_),
    .ZN(_11_)
  );
  NAND2_X1 _41_ (
    .A1(mapping[1]),
    .A2(addri[2]),
    .ZN(_12_)
  );
  NAND2_X1 _42_ (
    .A1(addri[0]),
    .A2(_04_),
    .ZN(_13_)
  );
  AND2_X1 _43_ (
    .A1(_12_),
    .A2(_13_),
    .ZN(_14_)
  );
  NAND2_X1 _44_ (
    .A1(_11_),
    .A2(_14_),
    .ZN(addro[2])
  );
  NAND2_X1 _45_ (
    .A1(addri[5]),
    .A2(_01_),
    .ZN(_15_)
  );
  NAND2_X1 _46_ (
    .A1(mapping[1]),
    .A2(addri[3]),
    .ZN(_16_)
  );
  NAND2_X1 _47_ (
    .A1(addri[1]),
    .A2(_04_),
    .ZN(_17_)
  );
  AND2_X1 _48_ (
    .A1(_16_),
    .A2(_17_),
    .ZN(_18_)
  );
  NAND2_X1 _49_ (
    .A1(_15_),
    .A2(_18_),
    .ZN(addro[3])
  );
  NAND2_X1 _50_ (
    .A1(addri[0]),
    .A2(_01_),
    .ZN(_19_)
  );
  NAND2_X1 _51_ (
    .A1(mapping[1]),
    .A2(addri[4]),
    .ZN(_20_)
  );
  NAND2_X1 _52_ (
    .A1(addri[2]),
    .A2(_04_),
    .ZN(_21_)
  );
  AND2_X1 _53_ (
    .A1(_20_),
    .A2(_21_),
    .ZN(_22_)
  );
  NAND2_X1 _54_ (
    .A1(_19_),
    .A2(_22_),
    .ZN(addro[4])
  );
  NAND2_X1 _55_ (
    .A1(addri[1]),
    .A2(_01_),
    .ZN(_23_)
  );
  NAND2_X1 _56_ (
    .A1(mapping[1]),
    .A2(addri[5]),
    .ZN(_24_)
  );
  NAND2_X1 _57_ (
    .A1(addri[3]),
    .A2(_04_),
    .ZN(_25_)
  );
  AND2_X1 _58_ (
    .A1(_24_),
    .A2(_25_),
    .ZN(_26_)
  );
  NAND2_X1 _59_ (
    .A1(_23_),
    .A2(_26_),
    .ZN(addro[5])
  );
endmodule
