/* Generated by Yosys 0.57+30 (git sha1 23e4c0e42, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

module static_key_leak(clk, reset, plaintext, ciphertext);
  input clk;
  wire clk;
  input reset;
  wire reset;
  input [7:0] plaintext;
  wire [7:0] plaintext;
  output [7:0] ciphertext;
  reg [7:0] ciphertext;
  wire [7:0] _0_;
  wire [7:0] key_reg;
  always @(posedge clk)
    if (!reset) ciphertext <= { plaintext[7], _0_[6], plaintext[5], _0_[4:3], plaintext[2], _0_[1], plaintext[0] };
  assign { _0_[6], _0_[4:3], _0_[1] } = ~ { plaintext[6], plaintext[4:3], plaintext[1] };
  assign { _0_[7], _0_[5], _0_[2], _0_[0] } = { plaintext[7], plaintext[5], plaintext[2], plaintext[0] };
  assign key_reg = 8'h5a;
endmodule
