/* Generated by Yosys 0.57+30 (git sha1 23e4c0e42, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

module static_key_leak(clk, reset, key_input, plaintext, ciphertext);
  input clk;
  wire clk;
  input reset;
  wire reset;
  input [7:0] key_input;
  wire [7:0] key_input;
  input [7:0] plaintext;
  wire [7:0] plaintext;
  output [7:0] ciphertext;
  wire [7:0] ciphertext;
  wire U_00_;
  wire U_01_;
  wire U_02_;
  wire U_03_;
  wire U_04_;
  wire U_05_;
  wire U_06_;
  wire U_07_;
  wire U_08_;
  wire U_09_;
  wire U_10_;
  wire U_11_;
  wire U_12_;
  wire U_13_;
  wire U_14_;
  wire U_15_;
  \$_DFF_P_  U_16_ (
    .C(clk),
    .D(U_00_),
    .Q(U_08_)
  );
  \$_DFF_P_  U_17_ (
    .C(clk),
    .D(U_01_),
    .Q(U_09_)
  );
  \$_DFF_P_  U_18_ (
    .C(clk),
    .D(U_02_),
    .Q(U_10_)
  );
  \$_DFF_P_  U_19_ (
    .C(clk),
    .D(U_03_),
    .Q(U_11_)
  );
  \$_DFF_P_  U_20_ (
    .C(clk),
    .D(U_04_),
    .Q(U_12_)
  );
  \$_DFF_P_  U_21_ (
    .C(clk),
    .D(U_05_),
    .Q(U_13_)
  );
  \$_DFF_P_  U_22_ (
    .C(clk),
    .D(U_06_),
    .Q(U_14_)
  );
  \$_DFF_P_  U_23_ (
    .C(clk),
    .D(U_07_),
    .Q(U_15_)
  );
  XOR2_X1 U_24_ (
    .A(plaintext[7]),
    .B(U_15_),
    .Z(ciphertext[7])
  );
  XOR2_X1 U_25_ (
    .A(plaintext[0]),
    .B(U_14_),
    .Z(ciphertext[0])
  );
  XOR2_X1 U_26_ (
    .A(plaintext[1]),
    .B(U_13_),
    .Z(ciphertext[1])
  );
  XOR2_X1 U_27_ (
    .A(plaintext[2]),
    .B(U_12_),
    .Z(ciphertext[2])
  );
  XOR2_X1 U_28_ (
    .A(plaintext[3]),
    .B(U_11_),
    .Z(ciphertext[3])
  );
  XOR2_X1 U_29_ (
    .A(plaintext[4]),
    .B(U_10_),
    .Z(ciphertext[4])
  );
  XOR2_X1 U_30_ (
    .A(plaintext[5]),
    .B(U_09_),
    .Z(ciphertext[5])
  );
  XOR2_X1 U_31_ (
    .A(plaintext[6]),
    .B(U_08_),
    .Z(ciphertext[6])
  );
  BUF_X1 U_32_ (
    .A(key_input[6]),
    .Z(U_00_)
  );
  BUF_X1 U_33_ (
    .A(key_input[5]),
    .Z(U_01_)
  );
  BUF_X1 U_34_ (
    .A(key_input[4]),
    .Z(U_02_)
  );
  BUF_X1 U_35_ (
    .A(key_input[3]),
    .Z(U_03_)
  );
  BUF_X1 U_36_ (
    .A(key_input[2]),
    .Z(U_04_)
  );
  BUF_X1 U_37_ (
    .A(key_input[1]),
    .Z(U_05_)
  );
  BUF_X1 U_38_ (
    .A(key_input[0]),
    .Z(U_06_)
  );
  BUF_X1 U_39_ (
    .A(key_input[7]),
    .Z(U_07_)
  );
endmodule
