/* Generated by Yosys 0.57+30 (git sha1 23e4c0e42, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

module static_key_leak(clk, reset, plaintext, ciphertext);
  input clk;
  wire clk;
  input reset;
  wire reset;
  input [7:0] plaintext;
  wire [7:0] plaintext;
  output [7:0] ciphertext;
  wire [7:0] ciphertext;
  wire U_00_;
  wire U_01_;
  wire U_02_;
  wire U_03_;
  wire U_04_;
  wire U_05_;
  wire U_06_;
  wire U_07_;
  wire U_08_;
  wire U_09_;
  wire U_10_;
  wire U_11_;
  wire U_12_;
  wire U_13_;
  wire U_14_;
  wire U_15_;
  wire U_16_;
  wire U_17_;
  wire U_18_;
  wire U_19_;
  wire U_20_;
  wire U_21_;
  wire U_22_;
  wire U_23_;
  wire U_24_;
  wire U_25_;
  wire U_26_;
  wire U_27_;
  wire U_28_;
  wire U_29_;
  wire U_30_;
  wire U_31_;
  wire U_32_;
  INV_X1 U_33_ (
    .A(reset),
    .ZN(U_08_)
  );
  NAND2_X1 U_34_ (
    .A1(ciphertext[0]),
    .A2(reset),
    .ZN(U_09_)
  );
  NAND2_X1 U_35_ (
    .A1(plaintext[0]),
    .A2(U_08_),
    .ZN(U_10_)
  );
  NAND2_X1 U_36_ (
    .A1(U_09_),
    .A2(U_10_),
    .ZN(U_00_)
  );
  NAND2_X1 U_37_ (
    .A1(reset),
    .A2(ciphertext[1]),
    .ZN(U_11_)
  );
  OR2_X1 U_38_ (
    .A1(plaintext[1]),
    .A2(reset),
    .ZN(U_12_)
  );
  NAND2_X1 U_39_ (
    .A1(U_11_),
    .A2(U_12_),
    .ZN(U_01_)
  );
  NAND2_X1 U_40_ (
    .A1(reset),
    .A2(ciphertext[2]),
    .ZN(U_13_)
  );
  NAND2_X1 U_41_ (
    .A1(U_08_),
    .A2(plaintext[2]),
    .ZN(U_14_)
  );
  NAND2_X1 U_42_ (
    .A1(U_13_),
    .A2(U_14_),
    .ZN(U_02_)
  );
  NAND2_X1 U_43_ (
    .A1(reset),
    .A2(ciphertext[3]),
    .ZN(U_15_)
  );
  OR2_X1 U_44_ (
    .A1(plaintext[3]),
    .A2(reset),
    .ZN(U_16_)
  );
  NAND2_X1 U_45_ (
    .A1(U_15_),
    .A2(U_16_),
    .ZN(U_03_)
  );
  NAND2_X1 U_46_ (
    .A1(reset),
    .A2(ciphertext[4]),
    .ZN(U_17_)
  );
  OR2_X1 U_47_ (
    .A1(plaintext[4]),
    .A2(reset),
    .ZN(U_18_)
  );
  NAND2_X1 U_48_ (
    .A1(U_17_),
    .A2(U_18_),
    .ZN(U_04_)
  );
  NAND2_X1 U_49_ (
    .A1(reset),
    .A2(ciphertext[5]),
    .ZN(U_19_)
  );
  NAND2_X1 U_50_ (
    .A1(U_08_),
    .A2(plaintext[5]),
    .ZN(U_20_)
  );
  NAND2_X1 U_51_ (
    .A1(U_19_),
    .A2(U_20_),
    .ZN(U_05_)
  );
  NAND2_X1 U_52_ (
    .A1(reset),
    .A2(ciphertext[6]),
    .ZN(U_21_)
  );
  OR2_X1 U_53_ (
    .A1(plaintext[6]),
    .A2(reset),
    .ZN(U_22_)
  );
  NAND2_X1 U_54_ (
    .A1(U_21_),
    .A2(U_22_),
    .ZN(U_06_)
  );
  NAND2_X1 U_55_ (
    .A1(reset),
    .A2(ciphertext[7]),
    .ZN(U_23_)
  );
  NAND2_X1 U_56_ (
    .A1(U_08_),
    .A2(plaintext[7]),
    .ZN(U_24_)
  );
  NAND2_X1 U_57_ (
    .A1(U_23_),
    .A2(U_24_),
    .ZN(U_07_)
  );
  DFF_X1 U_58_ (
    .CK(clk),
    .D(U_00_),
    .Q(ciphertext[0]),
    .QN(U_32_)
  );
  DFF_X1 U_59_ (
    .CK(clk),
    .D(U_01_),
    .Q(ciphertext[1]),
    .QN(U_31_)
  );
  DFF_X1 U_60_ (
    .CK(clk),
    .D(U_02_),
    .Q(ciphertext[2]),
    .QN(U_30_)
  );
  DFF_X1 U_61_ (
    .CK(clk),
    .D(U_03_),
    .Q(ciphertext[3]),
    .QN(U_29_)
  );
  DFF_X1 U_62_ (
    .CK(clk),
    .D(U_04_),
    .Q(ciphertext[4]),
    .QN(U_28_)
  );
  DFF_X1 U_63_ (
    .CK(clk),
    .D(U_05_),
    .Q(ciphertext[5]),
    .QN(U_27_)
  );
  DFF_X1 U_64_ (
    .CK(clk),
    .D(U_06_),
    .Q(ciphertext[6]),
    .QN(U_26_)
  );
  DFF_X1 U_65_ (
    .CK(clk),
    .D(U_07_),
    .Q(ciphertext[7]),
    .QN(U_25_)
  );
endmodule
