/* Generated by Yosys 0.57+30 (git sha1 23e4c0e42, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

module static_key_leak(clk, reset, key_input, plaintext, ciphertext);
  input clk;
  wire clk;
  input reset;
  wire reset;
  input [7:0] key_input;
  wire [7:0] key_input;
  input [7:0] plaintext;
  wire [7:0] plaintext;
  output [7:0] ciphertext;
  wire [7:0] ciphertext;
  wire U_00_;
  wire U_01_;
  wire U_02_;
  wire U_03_;
  wire U_04_;
  wire U_05_;
  wire U_06_;
  wire U_07_;
  wire U_08_;
  wire U_09_;
  wire U_10_;
  wire U_11_;
  wire U_12_;
  wire U_13_;
  wire U_14_;
  wire U_15_;
  wire U_16_;
  wire U_17_;
  wire U_18_;
  wire U_19_;
  wire U_20_;
  wire U_21_;
  wire U_22_;
  wire U_23_;
  wire U_24_;
  wire U_25_;
  wire U_26_;
  wire U_27_;
  wire U_28_;
  wire U_29_;
  wire U_30_;
  wire U_31_;
  wire U_32_;
  wire U_33_;
  wire U_34_;
  wire U_35_;
  wire U_36_;
  wire key_loaded;
  wire [7:0] key_reg;
  INV_X1 U_37_ (
    .A(key_loaded),
    .ZN(U_09_)
  );
  XOR2_X1 U_38_ (
    .A(key_reg[0]),
    .B(plaintext[0]),
    .Z(ciphertext[0])
  );
  XOR2_X1 U_39_ (
    .A(key_reg[1]),
    .B(plaintext[1]),
    .Z(ciphertext[1])
  );
  XOR2_X1 U_40_ (
    .A(key_reg[2]),
    .B(plaintext[2]),
    .Z(ciphertext[2])
  );
  XOR2_X1 U_41_ (
    .A(key_reg[3]),
    .B(plaintext[3]),
    .Z(ciphertext[3])
  );
  XOR2_X1 U_42_ (
    .A(key_reg[4]),
    .B(plaintext[4]),
    .Z(ciphertext[4])
  );
  XOR2_X1 U_43_ (
    .A(key_reg[5]),
    .B(plaintext[5]),
    .Z(ciphertext[5])
  );
  XOR2_X1 U_44_ (
    .A(key_reg[6]),
    .B(plaintext[6]),
    .Z(ciphertext[6])
  );
  XOR2_X1 U_45_ (
    .A(key_reg[7]),
    .B(plaintext[7]),
    .Z(ciphertext[7])
  );
  AND2_X1 U_46_ (
    .A1(U_09_),
    .A2(reset),
    .ZN(U_10_)
  );
  NAND2_X1 U_47_ (
    .A1(U_09_),
    .A2(reset),
    .ZN(U_11_)
  );
  NAND2_X1 U_48_ (
    .A1(key_input[5]),
    .A2(U_10_),
    .ZN(U_12_)
  );
  NAND2_X1 U_49_ (
    .A1(key_reg[5]),
    .A2(U_11_),
    .ZN(U_13_)
  );
  NAND2_X1 U_50_ (
    .A1(U_12_),
    .A2(U_13_),
    .ZN(U_00_)
  );
  NAND2_X1 U_51_ (
    .A1(key_input[6]),
    .A2(U_10_),
    .ZN(U_14_)
  );
  NAND2_X1 U_52_ (
    .A1(key_reg[6]),
    .A2(U_11_),
    .ZN(U_15_)
  );
  NAND2_X1 U_53_ (
    .A1(U_14_),
    .A2(U_15_),
    .ZN(U_01_)
  );
  NAND2_X1 U_54_ (
    .A1(key_input[7]),
    .A2(U_10_),
    .ZN(U_16_)
  );
  NAND2_X1 U_55_ (
    .A1(key_reg[7]),
    .A2(U_11_),
    .ZN(U_17_)
  );
  NAND2_X1 U_56_ (
    .A1(U_16_),
    .A2(U_17_),
    .ZN(U_02_)
  );
  NAND2_X1 U_57_ (
    .A1(key_input[0]),
    .A2(U_10_),
    .ZN(U_18_)
  );
  NAND2_X1 U_58_ (
    .A1(key_reg[0]),
    .A2(U_11_),
    .ZN(U_19_)
  );
  NAND2_X1 U_59_ (
    .A1(U_18_),
    .A2(U_19_),
    .ZN(U_04_)
  );
  NAND2_X1 U_60_ (
    .A1(key_input[1]),
    .A2(U_10_),
    .ZN(U_20_)
  );
  NAND2_X1 U_61_ (
    .A1(key_reg[1]),
    .A2(U_11_),
    .ZN(U_21_)
  );
  NAND2_X1 U_62_ (
    .A1(U_20_),
    .A2(U_21_),
    .ZN(U_05_)
  );
  NAND2_X1 U_63_ (
    .A1(key_input[2]),
    .A2(U_10_),
    .ZN(U_22_)
  );
  NAND2_X1 U_64_ (
    .A1(key_reg[2]),
    .A2(U_11_),
    .ZN(U_23_)
  );
  NAND2_X1 U_65_ (
    .A1(U_22_),
    .A2(U_23_),
    .ZN(U_06_)
  );
  NAND2_X1 U_66_ (
    .A1(key_input[3]),
    .A2(U_10_),
    .ZN(U_24_)
  );
  NAND2_X1 U_67_ (
    .A1(key_reg[3]),
    .A2(U_11_),
    .ZN(U_25_)
  );
  NAND2_X1 U_68_ (
    .A1(U_24_),
    .A2(U_25_),
    .ZN(U_07_)
  );
  NAND2_X1 U_69_ (
    .A1(key_input[4]),
    .A2(U_10_),
    .ZN(U_26_)
  );
  NAND2_X1 U_70_ (
    .A1(key_reg[4]),
    .A2(U_11_),
    .ZN(U_27_)
  );
  NAND2_X1 U_71_ (
    .A1(U_26_),
    .A2(U_27_),
    .ZN(U_08_)
  );
  BUF_X1 U_72_ (
    .A(reset),
    .Z(U_03_)
  );
  DFF_X1 U_73_ (
    .CK(clk),
    .D(U_00_),
    .Q(key_reg[5]),
    .QN(U_36_)
  );
  DFF_X1 U_74_ (
    .CK(clk),
    .D(U_01_),
    .Q(key_reg[6]),
    .QN(U_35_)
  );
  DFF_X1 U_75_ (
    .CK(clk),
    .D(U_02_),
    .Q(key_reg[7]),
    .QN(U_34_)
  );
  DFF_X1 U_76_ (
    .CK(clk),
    .D(U_03_),
    .Q(key_loaded),
    .QN(U_33_)
  );
  DFF_X1 U_77_ (
    .CK(clk),
    .D(U_04_),
    .Q(key_reg[0]),
    .QN(U_32_)
  );
  DFF_X1 U_78_ (
    .CK(clk),
    .D(U_05_),
    .Q(key_reg[1]),
    .QN(U_31_)
  );
  DFF_X1 U_79_ (
    .CK(clk),
    .D(U_06_),
    .Q(key_reg[2]),
    .QN(U_30_)
  );
  DFF_X1 U_80_ (
    .CK(clk),
    .D(U_07_),
    .Q(key_reg[3]),
    .QN(U_29_)
  );
  DFF_X1 U_81_ (
    .CK(clk),
    .D(U_08_),
    .Q(key_reg[4]),
    .QN(U_28_)
  );
endmodule
