/* Generated by Yosys 0.57+30 (git sha1 23e4c0e42, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

module static_key_leak(clk, reset, plaintext, ciphertext);
  input clk;
  wire clk;
  input reset;
  wire reset;
  input [7:0] plaintext;
  wire [7:0] plaintext;
  output [7:0] ciphertext;
  wire [7:0] ciphertext;
  wire U__00_;
  wire U__01_;
  wire U__02_;
  wire U__03_;
  wire U__04_;
  wire U__05_;
  wire U__06_;
  wire U__07_;
  wire U__08_;
  wire U__09_;
  wire U__10_;
  wire U__11_;
  wire U__12_;
  wire U__13_;
  wire U__14_;
  wire U__15_;
  wire U__16_;
  wire U__17_;
  wire U__18_;
  wire U__19_;
  wire U__20_;
  wire U__21_;
  wire U__22_;
  wire U__23_;
  wire U__24_;
  wire U__25_;
  wire U__26_;
  wire U__27_;
  wire U__28_;
  wire U__29_;
  wire U__30_;
  wire U__31_;
  wire U__32_;
  INV_X1 U__33_ (
    .A(reset),
    .ZN(U__08_)
  );
  NAND2_X1 U__34_ (
    .A1(ciphertext[0]),
    .A2(reset),
    .ZN(U__09_)
  );
  NAND2_X1 U__35_ (
    .A1(plaintext[0]),
    .A2(U__08_),
    .ZN(U__10_)
  );
  NAND2_X1 U__36_ (
    .A1(U__09_),
    .A2(U__10_),
    .ZN(U__00_)
  );
  NAND2_X1 U__37_ (
    .A1(reset),
    .A2(ciphertext[1]),
    .ZN(U__11_)
  );
  OR2_X1 U__38_ (
    .A1(plaintext[1]),
    .A2(reset),
    .ZN(U__12_)
  );
  NAND2_X1 U__39_ (
    .A1(U__11_),
    .A2(U__12_),
    .ZN(U__01_)
  );
  NAND2_X1 U__40_ (
    .A1(reset),
    .A2(ciphertext[2]),
    .ZN(U__13_)
  );
  NAND2_X1 U__41_ (
    .A1(U__08_),
    .A2(plaintext[2]),
    .ZN(U__14_)
  );
  NAND2_X1 U__42_ (
    .A1(U__13_),
    .A2(U__14_),
    .ZN(U__02_)
  );
  NAND2_X1 U__43_ (
    .A1(reset),
    .A2(ciphertext[3]),
    .ZN(U__15_)
  );
  OR2_X1 U__44_ (
    .A1(plaintext[3]),
    .A2(reset),
    .ZN(U__16_)
  );
  NAND2_X1 U__45_ (
    .A1(U__15_),
    .A2(U__16_),
    .ZN(U__03_)
  );
  NAND2_X1 U__46_ (
    .A1(reset),
    .A2(ciphertext[4]),
    .ZN(U__17_)
  );
  OR2_X1 U__47_ (
    .A1(plaintext[4]),
    .A2(reset),
    .ZN(U__18_)
  );
  NAND2_X1 U__48_ (
    .A1(U__17_),
    .A2(U__18_),
    .ZN(U__04_)
  );
  NAND2_X1 U__49_ (
    .A1(reset),
    .A2(ciphertext[5]),
    .ZN(U__19_)
  );
  NAND2_X1 U__50_ (
    .A1(U__08_),
    .A2(plaintext[5]),
    .ZN(U__20_)
  );
  NAND2_X1 U__51_ (
    .A1(U__19_),
    .A2(U__20_),
    .ZN(U__05_)
  );
  NAND2_X1 U__52_ (
    .A1(reset),
    .A2(ciphertext[6]),
    .ZN(U__21_)
  );
  OR2_X1 U__53_ (
    .A1(plaintext[6]),
    .A2(reset),
    .ZN(U__22_)
  );
  NAND2_X1 U__54_ (
    .A1(U__21_),
    .A2(U__22_),
    .ZN(U__06_)
  );
  NAND2_X1 U__55_ (
    .A1(reset),
    .A2(ciphertext[7]),
    .ZN(U__23_)
  );
  NAND2_X1 U__56_ (
    .A1(U__08_),
    .A2(plaintext[7]),
    .ZN(U__24_)
  );
  NAND2_X1 U__57_ (
    .A1(U__23_),
    .A2(U__24_),
    .ZN(U__07_)
  );
  DFF_X1 U__58_ (
    .CK(clk),
    .D(U__00_),
    .Q(ciphertext[0]),
    .QN(U__32_)
  );
  DFF_X1 U__59_ (
    .CK(clk),
    .D(U__01_),
    .Q(ciphertext[1]),
    .QN(U__31_)
  );
  DFF_X1 U__60_ (
    .CK(clk),
    .D(U__02_),
    .Q(ciphertext[2]),
    .QN(U__30_)
  );
  DFF_X1 U__61_ (
    .CK(clk),
    .D(U__03_),
    .Q(ciphertext[3]),
    .QN(U__29_)
  );
  DFF_X1 U__62_ (
    .CK(clk),
    .D(U__04_),
    .Q(ciphertext[4]),
    .QN(U__28_)
  );
  DFF_X1 U__63_ (
    .CK(clk),
    .D(U__05_),
    .Q(ciphertext[5]),
    .QN(U__27_)
  );
  DFF_X1 U__64_ (
    .CK(clk),
    .D(U__06_),
    .Q(ciphertext[6]),
    .QN(U__26_)
  );
  DFF_X1 U__65_ (
    .CK(clk),
    .D(U__07_),
    .Q(ciphertext[7]),
    .QN(U__25_)
  );
endmodule
